[[redirects]]
  from = "/v6.js"
  to = "https://unpkg.com/pnpm@6.0.0-beta.1/dist/pnpm.js"
  status = 200
[[redirects]]
  from = "/v5.js"
  to = "https://unpkg.com/pnpm@5.18.9/dist/pnpm.js"
  status = 200
